// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void InsuranceQuote01_ValidInputs()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("24");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("finalQuote")).Click();
        {
            string value = "$5500";
            Assert.That(value, Is.EqualTo("$5500"));
        }
    }
    [Test]
    public void InsuranceQuote02_AccidentsAboveLimit()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("finalQuote")).Click();
        {
            string value = "No Insurance for you!!  Too many accidents - go take a course!";// driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void InsuranceQuote03_AgeReduction()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("finalQuote")).Click();
        {
            string value = "$3905";
            Assert.That(value, Is.EqualTo("$3905"));
        }
    }
    [Test]
    public void InsuranceQuote04_InvalidPhoneNumber()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("4372501494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void InsuranceQuote05_InvalidEmail()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.CssSelector(".card:nth-child(1)")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.CssSelector(".container")).Click();
        driver.FindElement(By.Id("email")).SendKeys("rohit7158");
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void InsuranceQuote06_InvalidPostalCode()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(2) > label")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("15");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.CssSelector(".form-row:nth-child(4)")).Click();
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void InsuranceQuote07_AgeOmitted()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }

    [Test]
    public void InsuranceQuote08_AccidentsOmitted()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div > .form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("4372501494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void InsuranceQuote09_ExperienceOmitted()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void InsuranceQuote10_LessAge()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("13");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".container")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
    }
    [Test]
    public void InsuranceQuote11_TooManyAccidents()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("4");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("finalQuote")).Click();
        {
            string value = "No Insurance for you!!  Too many accidents - go take a course!";
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void InsuranceQuote12_Rule1()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = "$5500";
            Assert.That(value, Is.EqualTo("$5500"));
        }
    }
    [Test]
    public void InsuranceQuote13_Rule2()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(2)")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("31");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = "$3905";
            Assert.That(value, Is.EqualTo("$3905"));
        }
    }
    [Test]
    public void InsuranceQuote14_InvalidExperience()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.CssSelector(".card-body")).Click();
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("50");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = "No Insurance for you!! Driver Age / Experience Not Correct";
            Assert.That(value, Is.EqualTo("No Insurance for you!! Driver Age / Experience Not Correct"));
        }
    }
    [Test]
    public void InsuranceQuote15_AgeError()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04%20-%20section%2003/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(610, 662);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohit");
        driver.FindElement(By.Id("lastName")).SendKeys("Chauhan");
        driver.FindElement(By.Id("address")).SendKeys("72 Goodsway");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7A 435");
        driver.FindElement(By.Id("email")).SendKeys("rohit7158@hotmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-250-1494");
        driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(1) > label")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("10");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("1");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("age")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
    }
}
